### ISSUE TITLE
add 3ds2  support

### ISSUE THREAD

**Issue by adam-col** [francoislevesque/vue-braintree#11]
Can we add support for 3ds? This is now required if a customer is from Europe so it's fairly important.

https://www.braintreepayments.com/blog/ready-for-3d-secure-2-0/

It would only require some minor changes

All the details are here https://developers.braintreepayments.com/guides/3d-secure/client-side/javascript/v3

**Comment by francoislevesque** [comment]
Now available in version 2.0.1 🙂 
With updated docs: https://francoislevesque.github.io/vue-braintree/configuration.html#enable-3d-secure

**Comment by adam-col** [comment]
Wow! That's amazing!

**Comment by adam-col** [comment]
Also there is one big "gotcha" with the extra details for the 3dsecure object which it might be worth adding to the docs - 

  givenName: 'Jill', // ASCII-printable characters required, else will throw a validation error
  surname: 'Doe', // ASCII-printable characters required, else will throw a validation error

In europe it's not uncommon to have non ASCII chars in names "Müller" is the most common surname in Germany.

Just these two fields require A-Z only a-z - Braintree say its something due to legacy creditcard processing software and suggest you just remove any other chars.

Thanks again for resolving this so quickly
