### ISSUE TITLE
Cardholder Name Collection

### ISSUE THREAD

**Issue by wsergent** [francoislevesque/vue-braintree#15]
It would be nice to be able to pass through an option to collect the Cardholder Name.
We use https://github.com/Cretezy/braintree-web-drop-in-react for our React front end, which allows this as an option - but for our Vue site, we need to implement a separate input field, and then collect that along with the braintree data in our success function to send to our backend. We also need to style and push this field into the inserted vue-braintree form.

Here is the documentation from braintree themselves:
https://developers.braintreepayments.com/guides/drop-in/customization/javascript/v3#collect-cardholder-name

**Comment by francoislevesque** [comment]
You can add a `card` prop like so:

```vue
<v-braintree 
    authorization="xxxxxxxxxxxxxxxxxxxxxx"
    :card="cardholderName: {
      required: false
      // to make cardholder name required
      // required: true
    }"
    @success="onSuccess"
    @error="onError"
></v-braintree>
```

I will add this to the documentation on the next release. Thanks for pointing this out! Let me know if this resolves your issue. 😁

**Comment by wsergent** [comment]
Absolutely fantastic! Thank you, works exactly as noted.
It would also be great to see this, and any other 'optional' items in the documentation, even if it's just a rough 'howto'.

Thank you again.
