### ISSUE TITLE
3D secure lookup error 404

### ISSUE THREAD

**Issue by PaddyLock** [francoislevesque/vue-braintree#18]
Hello, I have implimented 3D secure as per the docs

When I submit the payment form with 3DS I get the following

`Request URL: https://api.sandbox.braintreegateway.com/merchants/merchantid/client_api/v1/payment_methods/tokencc_bh_f455d4_brydg8_v24dbn_76jk7m_sg6/three_d_secure/lookup
`

which return an error 404 with

`{"error":{"message":"Record not found"},"fieldErrors":[]}`

The component uses a client token that I generate from the server and it works fine without 3DS.

**Comment by francoislevesque** [comment]
Are you still experiencing this issue? I'll try it on my end later this month and get back to you asap.

**Comment by PaddyLock** [comment]
I'm not getting this error anymore. I'm not sure what fixed it. You can close this issue, thanks.
