### ISSUE TITLE
How to get payment method nonce?

### ISSUE THREAD

**Issue by mgolshan** [francoislevesque/vue-braintree#2]
Hi.
It looks working nice. But, I believe if you add a bit more explanation or even some code samples to help to understand how to use it, would be much more appreciated.

For example, I can't find a way to get the payment method nonce. Or, I can't get how to submit the payload after I get a success event. Because no data is passed to the event listener.

How to add stuff to the axios call header? (like authorization)

**Comment by liamcharmer** [comment]
@mgolshan Currently doesn't seem possible which is ashame, the data that is passed however is under the key 'nonce' that is set by default. 

```
url="urlhere" 
```
is required in the component, and then as i say, it'll come under "nonce"

**Comment by francoislevesque** [comment]
With version 2.0.0, you can now retrieve the nonce like this:

```html
<v-braintree 
    authorization="xxxxxxxxxxxxxxxxxxxxxx"
    @success="onSuccess"
    @error="onError"
></v-braintree>
```
```javascript
export default {
  methods: {
    onSuccess (payload) {
      let nonce = payload.nonce;
      // Do something great with the nonce...
    },
    onError (error) {
      let message = error.message;
      // Whoops, an error has occured while trying to get the nonce
    }
  }
}
```

**Comment by mgolshan** [comment]
Thanks for the update.
