### ISSUE TITLE
Invalid JWT first time card details are submitted

### ISSUE THREAD

**Issue by PaddyLock** [francoislevesque/vue-braintree#20]
Hello, I have implemented the component with 3D secure. However whenever i submit the card details the first time I always get this error. The second time it works fine.

`BraintreeError {name: "BraintreeError", code: "THREEDS_CARDINAL_SDK_ERROR", message: "A general error has occurred with Cardinal. See description for more information.", type: "UNKNOWN", details: {…}}
code: "THREEDS_CARDINAL_SDK_ERROR"
details:
originalError:
code: 1020
description: "Invalid JWT. Error verifying and deserializing JWT."
__proto__: Object
__proto__: Object
message: "A general error has occurred with Cardinal. See description for more information."
name: "BraintreeError"
type: "UNKNOWN"
__proto__: Error
constructor: ƒ BraintreeError(options)
__proto__ `

**Comment by francoislevesque** [comment]
This looks like an error on Braintree's side 🤔 (see https://github.com/braintree/braintree-web/issues/426)
Could you try contacting them and see if they can fix the issue? Let me know if it helps!
