### ISSUE TITLE
Make url optional parameter, have emit "nonce-received" for success of retrieval of nonce

### ISSUE THREAD

**Issue by tdondich** [francoislevesque/vue-braintree#3]
Some people may want to define their own behavior for utilizing the nonce. Once nonce is received from braintree, we should always emit a 'nonce-received' event with the nonce as the message payload.

By having url an optional parameter, this will give developers maximum flexibility in receiving the nonce.

Furthermore, if for some reason, the nonce is not received, we should instead emit a nonce-failed message with the message.  Currently the message is echo'ed to the console, but instead we should just emit the error and let the developer determine what to do with it, even if the error is already shown in the drop-in UI.

**Comment by francoislevesque** [comment]
Hi there! You are absolutely right, I did this package very quickly 😅. 

I will soon release a v2 with more flexibility. Stay tuned!

**Comment by francoislevesque** [comment]
2.0.0 released! 🎉
Let me know what you think 🤗
